using osram.OSAS.Database.Framework;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;

namespace CustomerDataSharingLogic.ExternalConnections.TMDB
{
    //used in TMDB PEN for Gaudi data
    public class V_TMDB_FT_OSBE18_TEST : BaseBusinessObject
    {
        public String SERIAL_NUMBER { get; set; }
        public String DEVICE_DMC { get; set; }

        public static Dictionary<string, string> Columns = new Dictionary<string, string>()
        {
            {"-1", "1.laser_sn"},
            {"-2", "2.mflex_pn"},
            {"-3", "3.flex_sn"},
            {"-4", "4.module.beam_pointing_grade"},
            {"-5", "5.filename"},
            {"-6", "6.identifier"},
            {"-7", "7.2d_matrix_on_flex-->_scan"},
            {"-8", "8.2d_matrix_on_lid-->_scan"},
            {"-9", "9.ship_to"},
            {"-10", "10.year"},
            {"-11", "11.module_config"},
            {"-12", "12.workday_of_week_(day_of_fpc_assembly)"},
            {"-13", "13.ld_supplier_red"},
            {"-14", "14.ld_supplier_green_h"},
            {"-15", "15.ld_supplier_green_l"},
            {"-16", "16.ld_supplier_blue"},
            {"-17", "17.laser_version_red"},
            {"-18", "18.laser_version_green_h"},
            {"-19", "19.laser_version_green_l"},
            {"-20", "20.laser_version_blue"},
            {"-21", "21.beam_pointing_grade"},
            {"-22", "22.hermeticity_grade"},
            {"-23", "23.laser_cavity_red"},
            {"-24", "24.laser_cavity_green_h"},
            {"-25", "25.laser_cavity_green_l"},
            {"-26", "26.laser_cavity_blue"},
            {"-27", "27.laser_atmosphere"},
            {"-28", "28.module.test_conditions_red"},
            {"-29", "29.module.test_conditions_green_h"},
            {"-30", "30.module.test_conditions_green_l"},
            {"-31", "31.module.test_conditions_blue"},
            {"-32", "32.module.screening_conditions_red"},
            {"-33", "33.module.screening_conditions_green_h"},
            {"-34", "34.module.screening_conditions_green_l"},
            {"-35", "35.module.screening_conditions_blue"},
            {"-36", "36.wafer_sn_red"},
            {"-37", "37.wafer_sn_green_h"},
            {"-38", "38.wafer_sn_green_l"},
            {"-39", "39.wafer_sn_blue"},
            {"FT4_Ishort_G_10V", "40.module.ishort_gh"},
            {"FT4_Ishort_Glow_10V", "41.module.ishort_gl"},
            {"FT1_Ith_1_3C_R", "42.module.ith_r1_[ma]"},
            {"FT1_Ith_2_3C_R", "43.module.ith_r2_[ma]"},
            {"FT1_Ith_1_2C_G", "44.module.ith_gh1_[ma]"},
            {"FT1_Ith_2_2C_G", "45.module.ith_gh2_[ma]"},
            {"FT1_Ith_1_4C_Glow", "46.module.ith_gl1_[ma]"},
            {"FT1_Ith_2_4C_Glow", "47.module.ith_gl2_[ma]"},
            {"FT1_Ith_1_1C_B", "48.module.ith_b1_[ma]"},
            {"FT1_Ith_2_1C_B", "49.module.ith_b2_[ma]"},
            {"-50", "50.module.iop_r1"},
            {"-51", "51.module.iop_r2"},
            {"-52", "52.module.iop_gh1"},
            {"-53", "53.module.iop_gh2"},
            {"-54", "54.module.iop_gl1"},
            {"-55", "55.module.iop_gl2"},
            {"-56", "56.module.iop_b1"},
            {"-57", "57.module.iop_b2"},
            {"-58", "58.module.vop_r1"},
            {"-59", "59.module.vop_r2"},
            {"-60", "60.module.vop_gh1"},
            {"-61", "61.module.vop_gh2"},
            {"-62", "62.module.vop_gl1"},
            {"-63", "63.module.vop_gl2"},
            {"-64", "64.module.vop_b1"},
            {"-65", "65.module.vop_b2"},
            {"FT1_SE_1_3C_R", "66.module.slope_efficiency_r1"},
            {"FT1_SE_2_3C_R", "67.module.slope_efficiency_r2"},
            {"FT1_SE_1_2C_G", "68.module.slope_efficiency_gh1"},
            {"FT1_SE_2_2C_G", "69.module.slope_efficiency_gh2"},
            {"FT1_SE_1_4C_Glow", "70.module.slope_efficiency_gl1"},
            {"FT1_SE_2_4C_Glow", "71.module.slope_efficiency_gl2"},
            {"FT1_SE_1_1C_B", "72.module.slope_efficiency_b1"},
            {"FT1_SE_2_1C_B", "73.module.slope_efficiency_b2"},
            {"FT1_PKth_1_3C_R", "74.module.threshold_kink_r1"},
            {"FT1_PKth_2_3C_R", "75.module.threshold_kink_r2"},
            {"FT1_PKth_1_2C_G", "76.module.threshold_kink_gh1"},
            {"FT1_PKth_2_2C_G", "77.module.threshold_kink_gh2"},
            {"FT1_PKth_1_4C_Glow", "78.module.threshold_kink_gl1"},
            {"FT1_PKth_2_4C_Glow", "79.module.threshold_kink_gl2"},
            {"FT1_PKth_1_1C_B", "80.module.threshold_kink_b1"},
            {"FT1_PKth_2_1C_B", "81.module.threshold_kink_b2"},
            {"FT1_CondPF_1_3C_R", "82.module.other_kink_r1"},
            {"FT1_CondPF_2_3C_R", "83.module.other_kink_r2"},
            {"FT1_CondPF_1_3C_R_H", "84.module.other_kink_r1_hc"},
            {"FT1_CondPF_2_3C_R_H", "85.module.other_kink_r2_hc"},
            {"FT1_CondPF_1_2C_G", "86.module.other_kink_gh1"},
            {"FT1_CondPF_2_2C_G", "87.module.other_kink_gh2"},
            {"FT1_CondPF_1_4C_Glow", "88.module.other_kink_gl1"},
            {"FT1_CondPF_2_4C_Glow", "89.module.other_kink_gl2"},
            {"FT1_CondPF_1_1C_B", "90.module.other_kink_b1"},
            {"FT1_CondPF_2_1C_B", "91.module.other_kink_b2"},
            {"FT1_WL50mid_1_3C_R", "92.module.wavelength_r1_[nm]"},
            {"FT1_WL50mid_2_3C_R", "93.module.wavelength_r2_[nm]"},
            {"FT1_WL50mid_1_2C_G", "94.module.wavelength_gh1_[nm]"},
            {"FT1_WL50mid_2_2C_G", "95.module.wavelength_gh2_[nm]"},
            {"FT1_WL50mid_1_4C_Glow", "96.module.wavelength_gl1_[nm]"},
            {"FT1_WL50mid_2_4C_Glow", "97.module.wavelength_gl2_[nm]"},
            {"FT1_WL50mid_1_1C_B", "98.module.wavelength_b1_[nm]"},
            {"FT1_WL50mid_2_1C_B", "99.module.wavelength_b2_[nm]"},
            {"FT1_WL_G_shift", "100.module.wavelength_separation_gh1-gh2_[nm]"},
            {"FT1_WL_Glow_shift", "101.module.wavelength_separation_gl2-gl1_[nm]"},
            {"FT4_PR_1_3C_R", "102.module.polarization_ratio_r1_[pct]"},
            {"FT4_PR_2_3C_R", "103.module.polarization_ratio_r2_[pct]"},
            {"FT4_PR_1_2C_G", "104.module.polarization_ratio_gh1_[pct]"},
            {"FT4_PR_2_2C_G", "105.module.polarization_ratio_gh2_[pct]"},
            {"FT4_PR_1_4C_Glow", "106.module.polarization_ratio_gl1_[pct]"},
            {"FT4_PR_2_4C_Glow", "107.module.polarization_ratio_gl2_[pct]"},
            {"FT4_PR_1_1C_B", "108.module.polarization_ratio_b1_[pct]"},
            {"FT4_PR_2_1C_B", "109.module.polarization_ratio_b2_[pct]"},
            {"-110", "110.module.polarization_angle_r1_[deg]"},
            {"-111", "111.module.polarization_angle_r2_[deg]"},
            {"-112", "112.module.polarization_angle_gh1_[deg]"},
            {"-113", "113.module.polarization_angle_gh2_[deg]"},
            {"-114", "114.module.polarization_angle_gl1_[deg]"},
            {"-115", "115.module.polarization_angle_gl2_[deg]"},
            {"-116", "116.module.polarization_angle_b1_[deg]"},
            {"-117", "117.module.polarization_angle_b2_[deg]"},
            {"-118", "118.module.extinction_ratio_r1_[pct]"},
            {"-119", "119.module.extinction_ratio_r2_[pct]"},
            {"-120", "120.module.extinction_ratio_gh1_[pct]"},
            {"-121", "121.module.extinction_ratio_gh2_[pct]"},
            {"-122", "122.module.extinction_ratio_gl1_[pct]"},
            {"-123", "123.module.extinction_ratio_gl2_[pct]"},
            {"-124", "124.module.extinction_ratio_b1_[pct]"},
            {"-125", "125.module.extinction_ratio_b2_[pct]"},
            {"FT2_sFWHMh_1_3C_R", "126.module.fwhm-sa_r1_[deg]"},
            {"FT2_sFWHMh_2_3C_R", "127.module.fwhm-sa_r2_[deg]"},
            {"FT2_sFWHMh_1_2C_G", "128.module.fwhm-sa_gh1_[deg]"},
            {"FT2_sFWHMh_2_2C_G", "129.module.fwhm-sa_gh2_[deg]"},
            {"FT2_sFWHMh_1_4C_Glow", "130.module.fwhm-sa_gl1_[deg]"},
            {"FT2_sFWHMh_2_4C_Glow", "131.module.fwhm-sa_gl2_[deg]"},
            {"FT2_sFWHMh_1_1C_B", "132.module.fwhm-sa_b1_[deg]"},
            {"FT2_sFWHMh_2_1C_B", "133.module.fwhm-sa_b2_[deg]"},
            {"FT2_sFWHMv_1_3C_R", "134.module.fwhm-fa_r1_[deg]"},
            {"FT2_sFWHMv_2_3C_R", "135.module.fwhm-fa_r2_[deg]"},
            {"FT2_sFWHMv_1_2C_G", "136.module.fwhm-fa_gh1_[deg]"},
            {"FT2_sFWHMv_2_2C_G", "137.module.fwhm-fa_gh2_[deg]"},
            {"FT2_sFWHMv_1_4C_Glow", "138.module.fwhm-fa_gl1_[deg]"},
            {"FT2_sFWHMv_2_4C_Glow", "139.module.fwhm-fa_gl2_[deg]"},
            {"FT2_sFWHMv_1_1C_B", "140.module.fwhm-fa_b1_[deg]"},
            {"FT2_sFWHMv_2_1C_B", "141.module.fwhm-fa_b2_[deg]"},
            {"FT2_Tilth_1_3C_R", "142.module.absolute_beam_pointing-sa_[deg]_r1"},
            {"FT2_Tilth_2_3C_R", "143.module.absolute_beam_pointing-sa_[deg]_r2"},
            {"FT2_Tilth_1_2C_G", "144.module.absolute_beam_pointing-sa_[deg]_gh1"},
            {"FT2_Tilth_2_2C_G", "145.module.absolute_beam_pointing-sa_[deg]_gh2"},
            {"FT2_Tilth_1_4C_Glow", "146.module.absolute_beam_pointing-sa_[deg]_gl1"},
            {"FT2_Tilth_2_4C_Glow", "147.module.absolute_beam_pointing-sa_[deg]_gl2"},
            {"FT2_Tilth_1_1C_B", "148.module.absolute_beam_pointing-sa_[deg]_b1"},
            {"FT2_Tilth_2_1C_B", "149.module.absolute_beam_pointing-sa_[deg]_b2"},
            {"FT2_Tiltv_1_3C_R", "150.module.absolute_beam_pointing-fa_[deg]_r1"},
            {"FT2_Tiltv_2_3C_R", "151.module.absolute_beam_pointing-fa_[deg]_r2"},
            {"FT2_Tiltv_1_2C_G", "152.module.absolute_beam_pointing-fa_[deg]_gh1"},
            {"FT2_Tiltv_2_2C_G", "153.module.absolute_beam_pointing-fa_[deg]_gh2"},
            {"FT2_Tiltv_1_4C_Glow", "154.module.absolute_beam_pointing-fa_[deg]_gl1"},
            {"FT2_Tiltv_2_4C_Glow", "155.module.absolute_beam_pointing-fa_[deg]_gl2"},
            {"FT2_Tiltv_1_1C_B", "156.module.absolute_beam_pointing-fa_[deg]_b1"},
            {"FT2_Tiltv_2_1C_B", "157.module.absolute_beam_pointing-fa_[deg]_b2"},
            {"FT2_Tilth_R1R2", "158.module.relative_beam_pointing-sa_[deg]_r1r2"},
            {"FT2_Tilth_G1G2", "159.module.relative_beam_pointing-sa_[deg]_gh1gh2"},
            {"FT2_Tilth_Glow1Glow2", "160.module.relative_beam_pointing-sa_[deg]_gl1gl2"},
            {"FT2_Tilth_B1B2", "161.module.relative_beam_pointing-sa_[deg]_b1b2"},
            {"FT2_Tilth_R1G1", "162.module.relative_beam_pointing-sa_[deg]_r1gh1"},
            {"FT2_Tilth_R2G1", "163.module.relative_beam_pointing-sa_[deg]_r2gh1"},
            {"FT2_Tilth_B1G1", "164.module.relative_beam_pointing-sa_[deg]_b1gh1"},
            {"FT2_Tilth_B2G1", "165.module.relative_beam_pointing-sa_[deg]_b2gh1"},
            {"FT2_Tilth_Glow1G1", "166.module.relative_beam_pointing-sa_[deg]_gl1gh1"},
            {"FT2_Tilth_Glow2G1", "167.module.relative_beam_pointing-sa_[deg]_gl2gh1"},
            {"FT2_Tiltv_R1R2", "168.module.relative_beam_pointing-fa_[deg]_r1r2"},
            {"FT2_Tiltv_G1G2", "169.module.relative_beam_pointing-fa_[deg]_gh1gh2"},
            {"FT2_Tiltv_Glow1Glow2", "170.module.relative_beam_pointing-fa_[deg]_gl1gl2"},
            {"FT2_Tiltv_B1B2", "171.module.relative_beam_pointing-fa_[deg]_b1b2"},
            {"FT2_Tiltv_R1G1", "172.module.relative_beam_pointing-fa_[deg]_r1gh1"},
            {"FT2_Tiltv_R2G1", "173.module.relative_beam_pointing-fa_[deg]_r2gh1"},
            {"FT2_Tiltv_B1G1", "174.module.relative_beam_pointing-fa_[deg]_b1gh1"},
            {"FT2_Tiltv_B2G1", "175.module.relative_beam_pointing-fa_[deg]_b2gh1"},
            {"FT2_Tiltv_Glow1G1", "176.module.relative_beam_pointing-fa_[deg]_gl1gh1"},
            {"FT2_Tiltv_Glow2G1", "177.module.relative_beam_pointing-fa_[deg]_gl2gh1"},
            {"-178", "178.module.beam_uniformity_sa_[pct]_r1"},
            {"-179", "179.module.beam_uniformity_sa_[pct]_r2"},
            {"-180", "180.module.beam_uniformity_sa_[pct]_gh1"},
            {"-181", "181.module.beam_uniformity_sa_[pct]_gh2"},
            {"-182", "182.module.beam_uniformity_sa_[pct]_gl1"},
            {"-183", "183.module.beam_uniformity_sa_[pct]_gl2"},
            {"-184", "184.module.beam_uniformity_sa_[pct]_b1"},
            {"-185", "185.module.beam_uniformity_sa_[pct]_b2"},
            {"-186", "186.module.beam_uniformity_fa_[pct]_r1"},
            {"-187", "187.module.beam_uniformity_fa_[pct]_r2"},
            {"-188", "188.module.beam_uniformity_fa_[pct]_gh1"},
            {"-189", "189.module.beam_uniformity_fa_[pct]_gh2"},
            {"-190", "190.module.beam_uniformity_fa_[pct]_gl1"},
            {"-191", "191.module.beam_uniformity_fa_[pct]_gl2"},
            {"-192", "192.module.beam_uniformity_fa_[pct]_b1"},
            {"-193", "193.module.beam_uniformity_fa_[pct]_b2"},
            {"FT2_sTEh_1_3C_R", "194.module.top_error-sa_r1"},
            {"FT2_sTEh_2_3C_R", "195.module.top_error-sa_r2"},
            {"FT2_sTEh_1_2C_G", "196.module.top_error-sa_gh1"},
            {"FT2_sTEh_2_2C_G", "197.module.top_error-sa_gh2"},
            {"FT2_sTEh_1_4C_Glow", "198.module.top_error-sa_gl1"},
            {"FT2_sTEh_2_4C_Glow", "199.module.top_error-sa_gl2"},
            {"FT2_sTEh_1_1C_B", "200.module.top_error-sa_b1"},
            {"FT2_sTEh_2_1C_B", "201.module.top_error-sa_b2"},
            {"FT2_sBEh_1_3C_R", "202.module.bot_error-sa_r1"},
            {"FT2_sBEh_2_3C_R", "203.module.bot_error-sa_r2"},
            {"FT2_sBEh_1_2C_G", "204.module.bot_error-sa_gh1"},
            {"FT2_sBEh_2_2C_G", "205.module.bot_error-sa_gh2"},
            {"FT2_sBEh_1_4C_Glow", "206.module.bot_error-sa_gl1"},
            {"FT2_sBEh_2_4C_Glow", "207.module.bot_error-sa_gl2"},
            {"FT2_sBEh_1_1C_B", "208.module.bot_error-sa_b1"},
            {"FT2_sBEh_2_1C_B", "209.module.bot_error-sa_b2"},
            {"FT2_sTEv_1_3C_R", "210.module.top_error-fa_r1"},
            {"FT2_sTEv_2_3C_R", "211.module.top_error-fa_r2"},
            {"FT2_sTEv_1_2C_G", "212.module.top_error-fa_gh1"},
            {"FT2_sTEv_2_2C_G", "213.module.top_error-fa_gh2"},
            {"FT2_sTEv_1_4C_Glow", "214.module.top_error-fa_gl1"},
            {"FT2_sTEv_2_4C_Glow", "215.module.top_error-fa_gl2"},
            {"FT2_sTEv_1_1C_B", "216.module.top_error-fa_b1"},
            {"FT2_sTEv_2_1C_B", "217.module.top_error-fa_b2"},
            {"FT2_sBEv_1_3C_R", "218.module.bot_error-fa_r1"},
            {"FT2_sBEv_2_3C_R", "219.module.bot_error-fa_r2"},
            {"FT2_sBEv_1_2C_G", "220.module.bot_error-fa_gh1"},
            {"FT2_sBEv_2_2C_G", "221.module.bot_error-fa_gh2"},
            {"FT2_sBEv_1_4C_Glow", "222.module.bot_error-fa_gl1"},
            {"FT2_sBEv_2_4C_Glow", "223.module.bot_error-fa_gl2"},
            {"FT2_sBEv_1_1C_B", "224.module.bot_error-fa_b1"},
            {"FT2_sBEv_2_1C_B", "225.module.bot_error-fa_b2"},
            {"FT1_VswpMx_1_3C_R", "226.module_Vf_Imax_r1"},
            {"FT1_VswpMx_2_3C_R", "227.module_Vf_Imax_r2"},
            {"FT1_VswpMx_1_2C_G", "228.module_Vf_Imax_gh1"},
            {"FT1_VswpMx_2_2C_G", "229.module_Vf_Imax_gh2"},
            {"FT1_VswpMx_1_4C_Glow", "230.module_Vf_Imax_gl1"},
            {"FT1_VswpMx_2_4C_Glow", "231.module_Vf_Imax_gl2"},
            {"FT1_VswpMx_1_1C_B", "232.module_Vf_Imax_b1"},
            {"FT1_VswpMx_2_1C_B", "233.module_Vf_Imax_b2"},
            {"FT1_PswpMx_1_3C_R", "234.module_Pop_Imax_r1"},
            {"FT1_PswpMx_2_3C_R", "235.module_Pop_Imax_r2"},
            {"FT1_PswpMx_1_2C_G", "236.module_Pop_Imax_gh1"},
            {"FT1_PswpMx_2_2C_G", "237.module_Pop_Imax_gh2"},
            {"FT1_PswpMx_1_4C_Glow", "238.module_Pop_Imax_gl1"},
            {"FT1_PswpMx_2_4C_Glow", "239.module_Pop_Imax_gl2"},
            {"FT1_PswpMx_1_1C_B", "240.module_Pop_Imax_b1"},
            {"FT1_PswpMx_2_1C_B", "241.module_Pop_Imax_b2"},
            {"-424", "Result"}
        };
        public Dictionary<string, double> ColumnValues = new Dictionary<string, double>();

        public static List<V_TMDB_FT_OSBE18_TEST> GetMeasurements(List<string> dmc)
        {
            var dataStatement = $@"SELECT * FROM 
(
    SELECT * FROM (
        SELECT device_dmc, operation_name, param_name, value, RANK() OVER(PARTITION BY device_dmc ORDER BY record_timestamp DESC) AS rnk FROM
        (select device_dmc, operation_name, record_timestamp, param_name, value from TMDB_DATA.V_TMDB_FT_OSBE18_TEST2 where operation_number = '7365' and device_dmc in ('{string.Join("', '", dmc)}')) d
    ) where rnk = 1
)
PIVOT(
    AVG(value) 
    FOR param_name
    IN ( 
        {String.Join($",\r\n        ", Columns.Keys.Where(k => !k.StartsWith("-")).Select(k => $"'{k}' as {k.ToUpper()}"))}
    )
)";
            var dataTable = TmdbDBConnection.GetData(dataStatement, null);
            var result = new List<V_TMDB_FT_OSBE18_TEST>();
            foreach (DataRow row in dataTable.Rows)
            {
                var item = new V_TMDB_FT_OSBE18_TEST()
                {
                    DEVICE_DMC = row["DEVICE_DMC"]?.ToString()
                };
                foreach (var attribute in Columns.Keys.Where(k => !k.StartsWith("-")))
                {
                    double value = 0;
                    if (double.TryParse(row[attribute.ToUpper()]?.ToString(), out value))
                        item.ColumnValues[attribute] = value;
                }
                result.Add(item);
            }
            return result;
        }
    }
}
